#!/bin/bash

cd ./

export START=./runme
# export ${ARCH}
# export ${CROSS_COMPILE}
clear
echo "¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨ ¨"
echo
echo "Choose your build action"
echo
echo "1.  Make"
echo
echo " Make with number of jobs per core:"
echo
echo "2.  Make -j2"
echo "3.  Make -j3"
echo "4.  Make -j4"
echo "5.  Make -j8"
echo
echo "0. Return to main menu"
echo
echo " Enter desired option number and press enter"
read OPT
case $OPT in
        0) $START ;;
	1) make ;;
        2) make -j2 ;;
	3) make -j3 ;;
	4) make -j4 ;;
	5) make -j8 ;;
esac

read -p "Press [ENTER] to continue"
clear
$START
